#pragma once

// Generated by proto2ue. Source: example/person.proto

#include "CoreMinimal.h"
#include "example/person.proto2ue.generated.h"

namespace example {

    UENUM(BlueprintType)
    enum class EColor : int32 {
        COLOR_UNSPECIFIED = 0,
        COLOR_RED = 1,
    };

    UENUM(BlueprintType)
    enum class EPersonMood : int32 {
        MOOD_UNSPECIFIED = 0,
        MOOD_HAPPY = 1,
    };

    USTRUCT(BlueprintType)
    struct FProtoOptionalPersonFString {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        bool bIsSet = false;
        UPROPERTY(BlueprintReadWrite)
        FString Value{};
    };

    USTRUCT(BlueprintType)
    struct FMeta {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        FProtoOptionalPersonFString created_by{};
    };

    USTRUCT(BlueprintType)
    struct FPersonAttributes {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        FProtoOptionalPersonFString nickname{};
    };

    USTRUCT(BlueprintType)
    struct FProtoOptionalPersonInt32 {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        bool bIsSet = false;
        UPROPERTY(BlueprintReadWrite)
        int32 Value{};
    };

    USTRUCT(BlueprintType)
    struct FProtoOptionalPersonEColor {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        bool bIsSet = false;
        UPROPERTY(BlueprintReadWrite)
        EColor Value{};
    };

    USTRUCT(BlueprintType)
    struct FProtoOptionalPersonFPersonAttributes {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        bool bIsSet = false;
        UPROPERTY(BlueprintReadWrite)
        FPersonAttributes Value{};
    };

    USTRUCT(BlueprintType)
    struct FProtoOptionalPersonEPersonMood {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        bool bIsSet = false;
        UPROPERTY(BlueprintReadWrite)
        EPersonMood Value{};
    };

    USTRUCT(BlueprintType)
    struct FPerson {
        GENERATED_BODY()
        UPROPERTY(BlueprintReadWrite)
        FProtoOptionalPersonInt32 id{};
        UPROPERTY(BlueprintReadWrite)
        TArray<float> scores{};
        UPROPERTY(BlueprintReadWrite)
        TMap<FString, FMeta> labels{};
        UPROPERTY(BlueprintReadWrite)
        FProtoOptionalPersonEColor primary_color{};
        UPROPERTY(BlueprintReadWrite)
        FProtoOptionalPersonFPersonAttributes attributes{};
        UPROPERTY(BlueprintReadWrite)
        FString email{};
        UPROPERTY(BlueprintReadWrite)
        FString phone{};
        UPROPERTY(BlueprintReadWrite)
        FProtoOptionalPersonEPersonMood mood{};
        // oneof contact: email, phone
    };

}  // namespace example

