#pragma once

// Generated by proto2ue. Source: example/person.proto

#include "CoreMinimal.h"

#include "example/person_proto2ue.generated.h"

UENUM(BlueprintType)
enum class EColor : int32 {
    COLOR_UNSPECIFIED = 0,
    COLOR_RED = 1,
};

UENUM(BlueprintType)
enum class EPersonMood : int32 {
    MOOD_UNSPECIFIED = 0,
    MOOD_HAPPY = 1,
};

USTRUCT(BlueprintType)
struct FProtoOptionalExamplePersonFString {
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    bool bIsSet = false;
    UPROPERTY(BlueprintReadWrite)
    FString Value{};
};

USTRUCT(BlueprintType)
struct FMeta {
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonFString created_by{};
};

USTRUCT(BlueprintType)
struct FPersonAttributes {
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonFString nickname{};
};

USTRUCT(BlueprintType)
struct FProtoOptionalExamplePersonInt32 {
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    bool bIsSet = false;
    UPROPERTY(BlueprintReadWrite)
    int32 Value{};
};

USTRUCT(BlueprintType)
struct FProtoOptionalExamplePersonEColor {
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    bool bIsSet = false;
    UPROPERTY(BlueprintReadWrite)
    EColor Value{};
};

USTRUCT(BlueprintType)
struct FProtoOptionalExamplePersonFPersonAttributes {
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    bool bIsSet = false;
    UPROPERTY(BlueprintReadWrite)
    FPersonAttributes Value{};
};

USTRUCT()
struct FProtoOptionalExamplePersonEPersonMood {
    GENERATED_BODY()
    UPROPERTY()
    bool bIsSet = false;
    UPROPERTY()
    EPersonMood Value{};
};

USTRUCT(BlueprintType)
struct FPerson {
    GENERATED_BODY()
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonInt32 id{};
    UPROPERTY(BlueprintReadWrite)
    TArray<float> scores{};
    UPROPERTY(BlueprintReadWrite)
    TMap<FString, FMeta> labels{};
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonEColor primary_color{};
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonFPersonAttributes attributes{};
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonFString email{};
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonFString phone{};
    UPROPERTY(BlueprintReadWrite)
    FProtoOptionalExamplePersonEPersonMood mood{};
    // oneof contact: email, phone
};

