#pragma once

// Generated by proto2ue. Source: example/person.proto

#include "CoreMinimal.h"
#include "example/person.proto2ue.generated.h"

namespace example {

    UENUM(BlueprintType)
    enum class EColor : int32 {
        COLOR_UNSPECIFIED = 0,
        COLOR_RED = 1,
    };

    UENUM(BlueprintType)
    enum class EPersonMood : int32 {
        MOOD_UNSPECIFIED = 0,
        MOOD_HAPPY = 1,
    };

    USTRUCT(BlueprintType)
    struct FMeta {
        GENERATED_BODY()

        UPROPERTY(BlueprintReadWrite)
        TOptional<FString> created_by{};
    };

    USTRUCT(BlueprintType)
    struct FPerson {
        GENERATED_BODY()

        UPROPERTY(BlueprintReadWrite)
        TOptional<int32> id{};
        UPROPERTY(BlueprintReadWrite)
        TArray<float> scores{};
        UPROPERTY(BlueprintReadWrite)
        TMap<FString, FMeta> labels{};
        UPROPERTY(BlueprintReadWrite)
        TOptional<EColor> primary_color{};
        UPROPERTY(BlueprintReadWrite)
        TOptional<FPersonAttributes> attributes{};
        UPROPERTY(BlueprintReadWrite)
        FString email{};
        UPROPERTY(BlueprintReadWrite)
        FString phone{};
        UPROPERTY(BlueprintReadWrite)
        TOptional<EPersonMood> mood{};
        // oneof contact: email, phone
    };

    USTRUCT(BlueprintType)
    struct FPersonAttributes {
        GENERATED_BODY()

        UPROPERTY(BlueprintReadWrite)
        TOptional<FString> nickname{};
    };

}  // namespace example

