// Generated by proto2ue. Source: example/person.proto
#include "example/person.proto2ue.h"

UE_NAMESPACE_BEGIN(example)

    namespace proto2ue {
        void RegisterGeneratedTypes() {}
    }  // namespace proto2ue

UE_NAMESPACE_END(example)

