// Generated by proto2ue. Source: example/person.proto
#include "example/person.proto2ue.h"

namespace example {

    namespace proto2ue {
        void RegisterGeneratedTypes() {}
    }  // namespace proto2ue

}  // namespace example

